DEVICE_PATH := device/unisoc/ums9621_1h10

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_SUPPORTS_64_BIT_APPS := true

# Assertion
TARGET_OTA_ASSERT_DEVICE := ums9621_1h10

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := ums9621_1h10
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := true

# Build Rule
ALLOW_MISSING_DEPENDENCIES := true

# Kernel —— 不编译内核、不打包 boot.img，vendorbootimage 目标只需要 ramdisk + dtb，
# 内核继续用原厂 boot 分区里的，不动
TARGET_KERNEL_ARCH := arm64
BOARD_RAMDISK_USE_LZ4 := true          # [已核实] 真机 vendor_boot ramdisk 是 lz4 legacy 格式
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_NO_KERNEL := true
BOARD_KERNEL_SEPARATED_DTBO := true

# Boot header v4 —— 以下地址值 [已核实]，来自对 boot_a.bin / vendor_boot_a.bin 的真实二进制头部解析
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8 bootconfig bootconfig
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x05400000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

# dtb —— 真机提取（dtb_a 分区本身是空的，真实 dtb 打包在 vendor_boot 内部，已提取还原）
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)

# Partitions —— 分区大小均为真机 blockdev --getsize64 实测值 [已核实]
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 104857600
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_SYSTEMIMAGE_PARTITION_TYPE := erofs
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
TARGET_COPY_OUT_VENDOR := vendor
BOARD_SUPER_PARTITION_SIZE := 5872025600
BOARD_SUPER_PARTITION_GROUPS := ums9621_dynamic_partitions
BOARD_UMS9621_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product system_ext odm vendor_dlkm
BOARD_UMS9621_DYNAMIC_PARTITIONS_SIZE := 5867831296

# Platform
TARGET_BOARD_PLATFORM := ums9621

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TW_THEME := portrait_hdpi
TW_INCLUDE_FASTBOOTD := true
TW_SCREEN_WIDTH := 320
TW_SCREEN_HEIGHT := 480
TARGET_SCREEN_DENSITY := 160
TW_USE_TOUCHSCREEN := true

# USB —— 来自真机 /sys/class/udc/ 实测 [已核实]
TARGET_USBCONTROLLER := musb-hdrc.1.auto

# Treble
BOARD_VNDK_VERSION := current

# Vendor_boot recovery ramdisk —— 已经被 Rongyue E5 同架构机型验证过可行
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

# Debug
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
